// Generated by Wrangler on Fri Apr 05 2024 11:56:04 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  ENVIRONMENT: string
  SOUNDS: R2Bucket
  DB: D1Database
}
