// Generated by Wrangler on Wed Apr 10 2024 20:52:23 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	ENVIRONMENT: string;
	SOUNDS: R2Bucket;
	DB: D1Database;
}
