compatibility_date = "2024-03-29"
compatibility_flags = [
  "nodejs_compat",
  "rpc"
]

[[d1_databases]]
binding = "DB"
database_name = "olga-db"
database_id = "a51efe05-83e7-4df0-96c2-8fc06d94c66c"

[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "olga-sounds"
