name = "olga"
compatibility_date = "2024-03-29"
compatibility_flags = [
  "nodejs_compat",
  "rpc"
]
pages_build_output_dir = "build/client"

[[d1_databases]]
binding = "DB"
database_name = "olga-production"
database_id = "d9217430-2e70-4b04-94b5-01f1412e519c"

[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "olga-sounds"
