compatibility_date = "2024-03-29"
compatibility_flags = [
  "nodejs_compat",
  "rpc"
]

[[d1_databases]]
binding = "DB"
database_name = "olga-tv"
database_id = "f6526f17-e0eb-474b-8a33-f8d152c96769"
preview_database_id = "DB"

[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "olga-sounds"
