compatibility_date = "2024-03-29"
compatibility_flags = [
  "nodejs_compat",
  "rpc"
]

[[d1_databases]]
binding = "DB"
database_name = "olga-db"
database_id = "7323a457-114b-4055-a35a-b1046a5d2202"
preview_database_id = "DB"

[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "olga-sounds"
