compatibility_date = "2024-03-29"
compatibility_flags = [
  "nodejs_compat",
  "rpc"
]

[[d1_databases]]
binding = "DB"
database_name = "olga-db"
database_id = "0382c705-acd5-4198-82f5-d9a0381a566f"
preview_database_id = "DB"

[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "olga-sounds"
