// This file is generated by npm run build:icons

export type IconName =
  | "cuando-eric-conocio-a-milton"
  | "enter"
  | "exit"
  | "generacion-dorada"
  | "google"
  | "hamburger-menu"
  | "heart"
  | "mi-primo-es-asi"
  | "olga"
  | "paraiso-fiscal"
  | "se-extrana-a-la-nona"
  | "seria-increible"
  | "sone-que-volaba"
